// Phoenix's built-in knowledge, used when no AI is connected (and shown in the Learn tab).
// Written to be accurate, plain and affirming. Where something is contested or is community language rather than
// a formal diagnosis, it says so. It contains no statistics on purpose.
//
// Each entry: id, title, terms (phrases that trigger it), what (what it is), why (what is going on), helps (what tends to help).

import { KB_BOOKS, GROUPS } from './kb-books.js';
import { KB_TRAINING } from './kb-training.js';

const KB_CORE = [
  {
    id: 'neurodiversity', title: 'Neurodiversity, neurodivergent, neurotypical',
    terms: ['neurodiversity', 'neurodivergent', 'neurodivergence', 'neurotypical', 'neurodiverse', 'neuro divergent', 'neuro-divergent'],
    what: 'Neurodiversity is the fact that human brains work in many different ways. Neurodivergent describes people whose minds work differently from the dominant norm, for example Autistic, ADHD, dyslexic, dyspraxic, dyscalculic, Tourettic or OCD people. Neurotypical describes people whose minds fit that norm. None of these words is a diagnosis or an insult.',
    why: 'The neurodiversity paradigm says this variation is natural, like differences in height or handedness. Many struggles come from environments and expectations built for only one kind of mind.',
    helps: 'You can use the words for yourself whether or not you have a formal diagnosis. Finding other neurodivergent people often makes things feel less lonely.',
  },
  {
    id: 'autism', title: 'Autism',
    terms: ['autism', 'autistic', 'asd', 'aspergers', "asperger's", 'asperger'],
    what: 'Autism is a lifelong neurotype. Autistic people often experience the senses more intensely or differently, think in deep, focused and pattern-seeking ways, communicate in their own style, and need predictability or particular conditions to feel well. It is a spectrum of different profiles, not a straight line from “a little” to “a lot”.',
    why: 'Autistic people are the authority on their own experience. Most of the difficulty in Autistic lives comes from a world that is loud, unpredictable, and demanding in ways that do not fit, and from being misunderstood.',
    helps: 'Understanding your own sensory, social and energy needs, building in rest, and finding people who get it. Many adults find a late diagnosis or self-identification explains a lot and brings relief.',
  },
  {
    id: 'adhd', title: 'ADHD',
    terms: ['adhd', 'add', 'attention deficit', 'hyperactivity'],
    what: 'ADHD is a neurotype where attention, energy and motivation work differently. It is less “can’t pay attention” and more “can’t steer attention on demand”. Attention is often strong for things that are interesting, new, urgent or meaningful, and hard for things that are not. It also often affects starting tasks, time, and emotional intensity.',
    why: 'The name is misleading. ADHD brains often work on interest, challenge, novelty and urgency rather than importance. That is a difference in how motivation works, not laziness or a lack of willpower.',
    helps: 'Making tasks tiny, visible and interesting; using timers and body doubling; reducing friction to start; and treating yourself the way you would treat a friend who struggles with the same thing. Medication helps many people. That is a decision to make with a prescriber.',
  },
  {
    id: 'audhd', title: 'AuDHD (Autistic and ADHD)',
    terms: ['audhd', 'autistic and adhd', 'adhd and autism', 'autism and adhd', 'actually autistic and adhd', 'both autism and adhd', 'both autistic and adhd'],
    what: 'AuDHD means being both Autistic and ADHD. It has been officially recognised as possible to have both since 2013. Many people describe it as being pulled two ways: one part craves routine and predictability, the other craves novelty and stimulation.',
    why: 'The two can hide each other or clash. For example, needing routine but getting bored by it, or wanting to socialise but running out of energy fast. This is common, and it is not you being inconsistent.',
    helps: 'Flexible structure (a loose routine with room to move), picking the need that matters most right now, and getting support that looks at both, not only one.',
  },
  {
    id: 'dyslexia', title: 'Dyslexia',
    terms: ['dyslexia', 'dyslexic'],
    what: 'Dyslexia is a difference in how the brain processes written language, affecting reading, spelling and sometimes working memory or organising information. It is unrelated to intelligence. Many dyslexic people are strong at big-picture thinking, storytelling, spotting patterns and creative problem-solving.',
    why: 'Written text is a code that dyslexic brains do not crack in the standard way. With the right tools and time, the difficulty shrinks a lot.',
    helps: 'Text-to-speech, speech-to-text, extra time, clear fonts and spacing, coloured overlays if they help you, and being allowed to show what you know in other ways. This app has a dyslexia-friendly text setting in Settings.',
  },
  {
    id: 'dyspraxia', title: 'Dyspraxia (DCD)',
    terms: ['dyspraxia', 'dyspraxic', 'dcd', 'developmental coordination', 'clumsy'],
    what: 'Dyspraxia, also called Developmental Coordination Disorder, is a difference in planning and coordinating movement. It can affect handwriting, cooking, driving, sport, spatial awareness, and doing steps in sequence.',
    why: 'It is a difference in how the brain plans and organises movement, and is not about effort or care. It often overlaps with ADHD and Autism.',
    helps: 'Extra time, tools that reduce fine-motor demands (keyboards, easy-grip equipment), breaking physical tasks into steps, and not being judged for spills, bumps or lateness.',
  },
  {
    id: 'dyscalculia', title: 'Dyscalculia',
    terms: ['dyscalculia', 'dyscalculic', 'maths anxiety', 'math anxiety'],
    what: 'Dyscalculia is a difference in understanding numbers, quantities and maths concepts. It can affect telling the time, handling money, estimating, and remembering number sequences.',
    why: 'It is not about intelligence or effort. Number sense works differently in the brain.',
    helps: 'Calculators and apps without shame, visual aids, checking with someone you trust for important sums, and asking for accommodations in study or work.',
  },
  {
    id: 'tourette', title: 'Tourette’s and tics',
    terms: ['tourette', "tourette's", 'tourettes', 'tics', 'tic disorder', 'tic'],
    what: 'Tourette’s syndrome is a neurotype involving tics: sudden movements or sounds that are hard to control. Tics often build up like an itch or a sneeze, and release brings relief. Only a minority of Tourettic people swear as a tic.',
    why: 'Tics are not habits or attention seeking. Holding them in takes effort and can be exhausting, and they often get worse with stress, excitement or being watched.',
    helps: 'Places where you do not have to suppress, people who do not stare or comment, rest, and support for stress. Tics and stims can look alike but tics tend to be less voluntary. You can have both.',
  },
  {
    id: 'ocd', title: 'OCD',
    terms: ['ocd', 'obsessive compulsive', 'obsessive-compulsive', 'intrusive thoughts'],
    what: 'OCD involves unwanted, distressing thoughts or urges (obsessions) and things a person feels they must do to ease the distress (compulsions). It is far more than liking things tidy. Intrusive thoughts, including frightening ones, are common in OCD and do not mean you want to act on them.',
    why: 'OCD is sometimes mistaken for, or overlaps with, Autistic routines and special interests, but the two feel different. OCD routines usually bring distress, while Autistic routines usually bring comfort.',
    helps: 'A clinician who understands both OCD and neurodivergence is worth looking for, because some standard treatments need adapting. If you are unsure which is which, you can describe both to them.',
  },
  {
    id: 'masking', title: 'Masking (camouflaging)',
    terms: ['masking', 'mask', 'camouflaging', 'camouflage', 'people pleasing', 'fawning'],
    what: 'Masking is hiding or suppressing your natural ways of being, and copying other people’s behaviour, to fit in and stay safe. Examples: forcing eye contact, hiding stims, rehearsing conversations, copying expressions, hiding sensory pain or hiding that you are lost.',
    why: 'Many neurodivergent people learn to mask because being themselves led to bullying, punishment or rejection. It is a survival skill. It is also tiring, and years of it can lead to burnout, anxiety and losing track of who you are.',
    helps: 'Unmasking is not all-or-nothing. You can start with places and people where it is safe, notice what you do automatically, and put your energy into what matters. You are allowed to decide when it is worth it.',
  },
  {
    id: 'burnout', title: 'Burnout (autistic and ADHD burnout)',
    terms: ['burnout', 'burn out', 'burnt out', 'burned out', 'autistic burnout', 'exhausted', 'exhaustion'],
    what: 'Neurodivergent burnout is a state of deep exhaustion, often with a loss of skills you used to have, lower tolerance for noise and demands, and needing more rest than usual. It follows a long stretch of pushing, masking, or living in an environment that does not fit.',
    why: 'It is not laziness or depression, though it can look like both. Your system has run out of capacity after too much strain for too long.',
    helps: 'Reduce demands as far as you can, rest without guilt, protect sleep and food, lower sensory load, and be patient. Recovery is usually slow, and pushing through tends to make it worse. Ask a professional who understands burnout if it lasts or you feel unsafe.',
  },
  {
    id: 'meltdown', title: 'Meltdowns',
    terms: ['meltdown', 'melt down', 'melting down', 'having a meltdown'],
    what: 'A meltdown is an intense, involuntary reaction when overwhelm has gone past what someone can hold. It can be crying, shouting, freezing, fleeing, or lashing out. It is not a tantrum, and it is not a choice.',
    why: 'Usually there has been a build-up: sensory load, demands, masking, hunger, tiredness or a change in plan. The meltdown is the release.',
    helps: 'During: reduce input (quiet, dim, less talking), make no demands, keep safe, and let it pass. After: rest, water and food, no blame. Later: look at what was building up, and what could be changed.',
  },
  {
    id: 'shutdown', title: 'Shutdowns',
    terms: ['shutdown', 'shut down', 'shutting down', 'going nonverbal', 'non verbal', 'nonverbal', 'lose words', 'lost my words'],
    what: 'A shutdown is when overload makes the system go quiet instead of loud: you might go silent, stop being able to speak or move much, feel numb or far away, or need to lie down. It is the other side of a meltdown.',
    why: 'It is your nervous system protecting you from too much. It is not sulking, ignoring anyone or being rude.',
    helps: 'Go somewhere quiet and safe, use text or gestures for communication, drop every demand, and give yourself time. Gentle sensory comfort (weight, warmth, soft things) helps some people. It usually passes.',
  },
  {
    id: 'stimming', title: 'Stimming',
    terms: ['stimming', 'stim', 'stims', 'stimmy', 'fidgeting', 'flapping', 'rocking'],
    what: 'Stimming is repetitive movement, sound or sensory input that regulates, soothes, focuses or expresses joy: flapping, rocking, pacing, humming, chewing, fidgeting, touching textures, watching lights, repeating words. Almost everyone stims a little, and neurodivergent people often stim more and need it more.',
    why: 'Stims are self-regulation and often joy. Being made to stop can raise stress and stop you thinking.',
    helps: 'Make room for stims. If a stim hurts you (for example hitting or biting yourself), you can swap it for something with similar sensory input that is safe, such as chewable jewellery or a firm squeeze.',
  },
  {
    id: 'sensory', title: 'Sensory overload and sensory needs',
    terms: ['sensory', 'overload', 'sensory overload', 'overstimulated', 'overstimulation', 'too loud', 'noise sensitive', 'sensitive to noise', 'sensitive to light', 'sensory processing', 'hypersensitive', 'hyposensitive'],
    what: 'Neurodivergent people often sense the world at a different intensity: sounds, lights, smells, textures and tastes can be painful or overwhelming (hypersensitivity), or hard to notice (hyposensitivity), sometimes both on the same day. Overload happens when input adds up past what you can process.',
    why: 'It is real, physical and cumulative. A noisy day can leave you with less capacity for everything else.',
    helps: 'Earplugs or noise-cancelling headphones, sunglasses or a cap, soft clothes, quiet breaks, lower lighting, giving yourself transition time, and planning recovery after loud events. Ask for adjustments: “I need a quieter table.” The Toolkit tab has a sensory reset.',
  },
  {
    id: 'interoception', title: 'Interoception',
    terms: ['interoception', 'interoceptive', 'body signals', 'forget to eat', 'forgot to eat', 'dont notice hunger', "don't notice hunger", 'need the toilet', 'notice thirst', 'body awareness'],
    what: 'Interoception is the sense of what is happening inside your body: hunger, thirst, needing the toilet, heartbeat, temperature, pain, tiredness, and the body side of emotions. Many neurodivergent people notice these signals late, weakly, or too intensely.',
    why: 'That is why you might realise at 4pm that you have not eaten or drunk anything, or why feelings can arrive as a vague “something is wrong”. It is a sense working differently, not carelessness.',
    helps: 'Use external cues: phone alarms, water bottle in sight, snacks near you, regular meal times, and a body check-in routine (“head to toe, what do I notice?”). The Check-in in the Toolkit is built for this.',
  },
  {
    id: 'alexithymia', title: 'Alexithymia',
    terms: ['alexithymia', 'alexithymic', "can't name my feelings", 'cant name my feelings', "don't know what i feel", 'dont know what i feel', "don't know how i feel", 'dont know how i feel', 'identify my emotions', 'identify emotions'],
    what: 'Alexithymia means finding it hard to identify and describe your own feelings. You may know something is off without knowing whether it is sadness, anger, hunger, tiredness or anxiety. It is common among Autistic people and also seen in ADHD.',
    why: 'It is not a lack of feeling. You feel, but the labelling is hard, often linked with interoception.',
    helps: 'Try naming sensations first (tight chest, hot face), use a feelings wheel or list, notice what happened just before, and take your time. Choosing “I do not know yet” is a fine answer.',
  },
  {
    id: 'monotropism', title: 'Monotropism',
    terms: ['monotropism', 'monotropic', 'hyperfocus', 'hyper focus', 'attention tunnel', 'attention tunnels', 'deep focus', 'flow state'],
    what: 'Monotropism is a theory, from Autistic researchers including Dinah Murray, Wenn Lawson and Mike Lesser, that Autistic minds tend to put a lot of attention into a few things at once, deeply, like a narrow, strong beam. ADHD people also describe hyperfocus that feels similar.',
    why: 'Deep focus is a strength, and it also makes switching, interruptions and transitions costly. That is why being pulled out of something can feel physically jarring, and why starting can be hard too.',
    helps: 'Give warnings before transitions, protect deep-focus time, use gentle timers, keep a note of where you were, and plan food and water breaks around the focus, not against it.',
  },
  {
    id: 'inertia', title: 'Autistic inertia and task initiation',
    terms: ['inertia', 'autistic inertia', "can't start", 'cant start', 'cannot start', 'task initiation', 'wall of awful', 'procrastinat', 'procrastination', 'paralysis', 'task paralysis', 'stuck', 'frozen', "can't get started", 'cant get started', 'getting started', 'motivation'],
    what: 'Task initiation is the step of getting going, and stopping or switching is the mirror image. Many neurodivergent people find these very hard even for things they want to do. In Autism this is sometimes called inertia. In ADHD it can be described as a wall in front of the task.',
    why: 'This is a brain-management difference (executive function), not laziness and not a lack of caring. Guilt and shame make the wall taller.',
    helps: 'Shrink the first step until it is almost silly (open the document, put one thing in the bin). Reduce friction, use a timer for two minutes, work next to someone (body doubling), pair a boring task with music, and drop the shame. The Toolkit has a task breaker and a focus timer.',
  },
  {
    id: 'executive', title: 'Executive function',
    terms: ['executive function', 'executive dysfunction', 'executive functioning', 'working memory', 'organising', 'organizing', 'planning', 'forgetful', 'forgetting things', 'disorganised', 'disorganized', 'decision fatigue', 'decision paralysis'],
    what: 'Executive function is the set of brain skills that manage everyday life: planning, starting, prioritising, switching, holding things in mind, and keeping track of time. In ADHD, Autism, dyspraxia and other neurotypes these often work differently and vary from day to day.',
    why: 'When they are not working, it can look like laziness or carelessness from the outside. On the inside it is more like trying to run a company with a receptionist who is on strike.',
    helps: 'Put things outside your head (lists, visual reminders, alarms), make routines automatic, use “launch pads” by the door, cut down decisions, and reduce the number of steps. Extra support is not cheating. It is the accommodation.',
  },
  {
    id: 'timeblind', title: 'Time blindness',
    terms: ['time blindness', 'time blind', 'lose track of time', 'losing track of time', 'always late', 'running late', 'time perception'],
    what: 'Time blindness is the common experience of struggling to feel how much time has passed or how long things take. Many ADHD and Autistic people say time feels like either “now” or “not now”.',
    why: 'It is a difference in how time is sensed and planned, not a character flaw.',
    helps: 'Make time visible (analogue clocks, visual timers), add padding, set alarms for leaving and for getting ready to leave, and guess how long a task will take and then double it.',
  },
  {
    id: 'rsd', title: 'Rejection sensitivity (RSD)',
    terms: ['rsd', 'rejection sensitivity', 'rejection sensitive', 'rejection sensitive dysphoria', 'fear of rejection', 'criticism hurts', 'took it badly', 'feel rejected'],
    what: 'Rejection sensitive dysphoria (RSD) is a term many ADHD and Autistic people use for very intense emotional pain in response to real or imagined rejection, criticism or disapproval. It is not a formal diagnosis. It is a description of a common lived experience.',
    why: 'Many neurodivergent people have had a lot of criticism and misunderstanding, and feel emotions intensely. The pain is real even if the rejection was only in your head.',
    helps: 'Name it (“this is the RSD feeling”), wait before replying to a message, check the story you are telling (“what else could this mean?”), ask a trusted person for a reality check, and be as gentle with yourself as you would be with a friend.',
  },
  {
    id: 'doubleempathy', title: 'The double empathy problem',
    terms: ['double empathy', 'double empathy problem', 'social skills', 'social deficit', 'bad at socialising', 'bad at socializing', 'awkward'],
    what: 'The double empathy problem, described by Autistic researcher Damian Milton in 2012, says that when people with very different ways of experiencing the world talk, both find it hard to understand each other. It is a two-way gap, not a one-way failing.',
    why: 'Research suggests that Autistic people often communicate very well with other Autistic people. The trouble seems to come from the mismatch, not from a missing skill.',
    helps: 'Spend time with people who share your communication style, say what you mean plainly, and ask for the same in return. You do not have to work out how to be “normal”.',
  },
  {
    id: 'pda', title: 'Demand avoidance and PDA',
    terms: ['pda', 'demand avoidance', 'pathological demand avoidance', 'pervasive drive for autonomy', 'i hate being told what to do', 'hate demands', 'demand avoidant'],
    what: 'Demand avoidance is a strong, anxiety-driven need to resist everyday demands, even ones you want to do. PDA is a profile some Autistic people identify with, and it is not an official diagnosis in the main manuals. Many people prefer the phrase “pervasive drive for autonomy”. Demands can be external (someone asks) or internal (I told myself I have to).',
    why: 'The pattern is about a nervous system that treats loss of control as a threat, not about being defiant or manipulative.',
    helps: 'Lower the pressure: turn demands into invitations or choices, share control, use humour and playfulness, add flexibility to routines, and reduce stacked demands. The person you are with can help by asking less and offering more.',
  },
  {
    id: 'specialinterests', title: 'Special interests and infodumping',
    terms: ['special interest', 'special interests', 'infodump', 'info dump', 'info-dump', 'infodumping', 'info dumping', 'passion', 'obsession with', 'deep interest'],
    what: 'A special interest is a deep, joyful, absorbing passion. Infodumping is enthusiastically sharing a lot about it, and for many neurodivergent people it is a way of showing care and connecting.',
    why: 'Interests often bring skill, joy, calm and identity, and they can be a route to work, community and friends. They are not something to be cured.',
    helps: 'Make room for them, find others who share them (online communities help), and ask friends whether they want an infodump now. Consent to an infodump is kind and works both ways.',
  },
  {
    id: 'bodydouble', title: 'Body doubling',
    terms: ['body doubling', 'body double', 'bodydouble', 'work alongside someone', 'work with someone in the room'],
    what: 'Body doubling is doing a task with someone else nearby (in person, or on a video call) who is also busy, and who does not have to help. Many ADHD and Autistic people find it makes starting and staying on task much easier.',
    why: 'Nobody is sure exactly why it works. Many people say another person’s calm presence gives their attention something to anchor to.',
    helps: 'Ask a friend, join an online co-working room, or use the Focus timer in the Toolkit, where Phoenix keeps you company while you work.',
  },
  {
    id: 'spoons', title: 'Spoon theory and energy budgeting',
    terms: ['spoon theory', 'spoons', 'out of spoons', 'no spoons', 'energy budget', 'energy budgeting', 'low energy', 'social battery', 'social battery'],
    what: 'Spoon theory, created by Christine Miserandino to explain living with chronic illness, imagines your daily energy as a limited number of spoons. Everything costs spoons, and neurodivergent people often pay extra for things others find free: noise, small talk, masking, unexpected change.',
    why: 'If you are tired and other people are not, it is not weakness. You are spending energy on things they do not notice.',
    helps: 'Plan the week by energy, not just time. Pair a draining task with recovery, do the important thing first, and protect what refills you. Track your energy in the Check-in in the Toolkit so you can spot the pattern.',
  },
  {
    id: 'identityfirst', title: 'Identity-first language',
    terms: ['identity first', 'identity-first', 'person first', 'person-first', 'autistic person or person with autism', 'what should i call myself', 'language we use'],
    what: 'Identity-first language (“Autistic person”, “ADHD person”) treats the neurotype as part of who someone is, like “Deaf person” or “queer person”. Person-first language (“person with autism”) treats it like something separate. Many Autistic people prefer identity-first. Others prefer person-first, and everyone gets to choose for themselves.',
    why: 'The words matter because they tell you whether a difference is being treated as part of a person or as a problem attached to them.',
    helps: 'Use the words the person uses for themselves. If you are unsure, ask.',
  },
  {
    id: 'selfid', title: 'Self-diagnosis and getting assessed',
    terms: ['self diagnosis', 'self-diagnosis', 'self diagnosed', 'self-diagnosed', 'self identify', 'self-identify', 'self identified', 'self-identified', 'do i have adhd', 'am i autistic', 'do i have autism', 'am i neurodivergent', 'imposter', 'impostor', 'not really autistic', 'fake', 'diagnosis', 'diagnosed', 'assessment'],
    what: 'Many people work out that they are neurodivergent through reading, lived experience of other neurodivergent people, and recognising themselves. Self-identification is valid and widely respected in neurodivergent communities. A formal diagnosis can help with access to support, but it can be expensive, slow, or out of reach.',
    why: 'Doubting yourself (“what if I am faking it?”) is extremely common, and it is often part of the pattern, because masking hides things even from you. Faking does not involve years of confused, tiring struggle.',
    helps: 'Read first-hand accounts by neurodivergent people, notice which ones ring true, and keep a list of examples from your life. If you want an assessment, look for someone neurodiversity-affirming and ask before booking what they do. I cannot diagnose you, and I can help you think it through.',
  },
  {
    id: 'ableism', title: 'Ableism and the social model',
    terms: ['ableism', 'ableist', 'social model', 'social model of disability', 'disability', 'disabled', 'accommodation', 'accommodations', 'reasonable adjustments', 'adjustments'],
    what: 'Ableism is treating disabled and neurodivergent people as lesser, or building the world as if everyone were the same. The social model of disability says people are disabled by barriers in the environment and attitudes, not just by their bodies or minds.',
    why: 'When something is hard for you, ask what in the environment could change. A quiet space, written instructions, flexible hours or a clear agenda can turn “can’t” into “can”.',
    helps: 'Asking for adjustments is fair and often legally protected (rules differ between countries). The Scripts in the Toolkit have wording for common requests, and I can help you tailor them.',
  },
  {
    id: 'functioninglabels', title: 'Functioning labels',
    terms: ['high functioning', 'low functioning', 'functioning label', 'functioning labels', 'mild autism', 'severe autism', 'level 1', 'level 2', 'level 3', 'support needs'],
    what: 'Terms like “high-functioning” and “low-functioning” try to sum up a whole person in a word. Many Autistic people find them harmful: “high-functioning” can hide real struggles and stop support, and “low-functioning” can hide ability and dismiss the person’s intelligence.',
    why: 'Support needs vary by day, setting and skill. Someone can be brilliant at one thing and need help with another, and this changes over time.',
    helps: 'Talk about specific needs and strengths instead: “I need written instructions” or “I can speak on good days and not on others”.',
  },
  {
    id: 'sleep', title: 'Sleep',
    terms: ['sleep', "can't sleep", 'cant sleep', 'insomnia', 'night owl', 'sleep trouble', 'trouble sleeping', 'stay up late', 'bedtime'],
    what: 'Sleep differences are very common among neurodivergent people: trouble winding down, a body clock that runs late, light sleep, and sensory things like sound, light or clothing keeping you awake.',
    why: 'A mind that keeps going, or a body that does not get the “time to sleep” signal clearly, is a difference in wiring and not a bad habit.',
    helps: 'Reduce sensory load at night (dark, cool, quiet, or steady white noise), wind down with something absorbing but calm, be careful with late caffeine and bright screens, and go easy on yourself. If sleep is a serious problem, mention it to a doctor. They can help with safe options.',
  },
  {
    id: 'transitions', title: 'Transitions and changes of plan',
    terms: ['transition', 'transitions', 'change of plan', 'changes', 'unexpected change', 'routine', 'routines', 'predictability', 'surprise'],
    what: 'Switching from one activity to another, or dealing with an unexpected change, takes real energy for many neurodivergent people. Routines and predictability lower the load.',
    why: 'When your attention is deeply in something, pulling it out costs effort. When your plan changes suddenly, your mind has to rebuild the whole picture.',
    helps: 'Ask for warnings (“ten minutes, then we leave”), keep a fixed anchor in the day, plan a bridging step (a snack, a stim, music), and give yourself time to re-plan when things change. It is fine to ask others for notice.',
  },
  {
    id: 'shame', title: 'Shame, self-criticism and being “too much”',
    terms: ['shame', 'ashamed', 'too much', 'not enough', 'im broken', "i'm broken", 'broken', 'defective', 'hate myself', 'self hatred', 'worthless', 'failure', "i'm a failure", 'im a failure', 'useless', 'lazy'],
    what: 'Many neurodivergent people have spent years being told they are lazy, rude, sensitive, dramatic or “not trying”. That builds a harsh inner voice.',
    why: 'That voice is a learned reaction to a lifetime of being judged by standards that were not built for you. It is not the truth about you.',
    helps: 'Try swapping “what is wrong with me?” for “what do I need?”. Notice what you are trying to do rather than what you did not manage. Find people who see you as you are. If the harsh voice is getting louder, please tell someone you trust or a professional who is neurodivergent-affirming.',
  },
];

export const KB = [...KB_CORE, ...KB_BOOKS, ...KB_TRAINING];
export { GROUPS };

// Ways to help when someone says "I need to..."
export const SCRIPTS = [
  { id: 'extra-time', title: 'Ask for more time', text: 'Thank you for the request. I want to do this properly, so I need until [day] to get it right. Could you confirm that works?' },
  { id: 'in-writing', title: 'Ask for instructions in writing', text: 'I take in information best in writing. Could you send that to me in an email or a message so I can go through it and reply properly?' },
  { id: 'say-no', title: 'Say no kindly', text: 'Thank you for asking. I am not able to take that on. I hope it goes well.' },
  { id: 'decline-social', title: 'Decline a social event', text: 'Thank you for inviting me. I am running low on energy, so I am going to stay in this time. I would really like to see you another time, maybe something quieter?' },
  { id: 'leave-early', title: 'Leave early, no explanation needed', text: 'I am going to head off now. It has been lovely to see you all.' },
  { id: 'quiet-space', title: 'Ask for a quieter space', text: 'The noise here makes it hard for me to think. Is there a quieter spot we could use, or could we move to somewhere with less background noise?' },
  { id: 'need-moment', title: 'Ask for a moment to think', text: 'I need a minute to think about that. Can I come back to you shortly?' },
  { id: 'overload', title: 'When you are overloaded and can’t talk', text: 'I am overloaded and may not be able to talk. It is not about you. I need quiet and time, and I will reach out when I am ready.' },
  { id: 'clear-agenda', title: 'Ask for a clear agenda', text: 'It would help me contribute if I could see the agenda and any questions ahead of the meeting. Would you be able to send them a day before?' },
  { id: 'directness', title: 'Ask for direct communication', text: 'I do best with clear, literal communication. If you need something from me, please say exactly what you mean. I will do the same for you.' },
  { id: 'stim', title: 'Explain stimming', text: 'I move or fidget because it helps me focus and stay calm. It does not mean I am not listening.' },
  { id: 'change-plans', title: 'When a plan changes and you need time', text: 'That is a change to what I expected, and I need a bit of time to adjust. Can I come back to you in [time] with how I would like to handle it?' },
  { id: 'accommodation-request', title: 'Formally ask for adjustments', text: 'I am [Autistic / ADHD / dyslexic / neurodivergent] and I am writing to ask for some adjustments that would help me do my best work: [list, for example: written instructions, a quieter workspace, flexible start times]. I am happy to talk about what would work for both of us.' },
];
